services:
  postgresfinnhjelpemiddelbff:
    hostname: postgresbff
    image: postgres:18
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./src/test/resources/postgres:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "log_statement=none"]

networks:
  bff-net:
